Rails:
  Enabled: true
AllCops:
  Exclude:
    - bin/**/*
    - db/**/*
    - script/**/*
    - spec/support/controller_helpers.rb
    - app/helpers/states_helper.rb
    - app/helpers/school_options_helper.rb
    - Guardfile
Metrics/LineLength:
  Enabled: false
Documentation:
  Enabled: false
Rails/HasAndBelongsToMany:
  Enabled: false
RedundantSelf:
  Enabled: false
